apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediamtx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Data-Space-Lab/MediaMTX-deployment.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dil-connector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
