apiVersion: v1
kind: Service
metadata:
  name: dil-connector-mediamtx
  namespace: dil-connector
  labels:
    app.kubernetes.io/name: mediamtx
    app.kubernetes.io/part-of: dil-connector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mediamtx
  ports:
    - name: api
      port: 9997
      targetPort: api
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dil-connector-mediamtx-rtsp
  namespace: dil-connector
  labels:
    app.kubernetes.io/name: mediamtx
    app.kubernetes.io/part-of: dil-connector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mediamtx
  ports:
    - name: rtsp
      port: 8554
      targetPort: rtsp
      protocol: TCP
